package com.order.bean;

public enum Category {
	GROCERY_AND_STAPLES, VEGETABLES_AND_FRUITS, PERSONAL_CARE,HOUSEHOLD_ITEMS,HOME_AND_KITCHEN,BISCUITS_SNACKS_CHOCOLATES, 
	BEVERAGES, BREAKFAST_AND_DAIRY;
	

}
